### PR TITLE
Digital Clock AM/PM and Double digit text added

### PR DESCRIPTION
**Pull request by Aravinthan-J**
Hey @boradesanket13 !!

**Given an support for this issue #81** 

Added some css for digital clock,

**Light Theme** 

1. Normal Mode 

image

2. Transparent Mode

image

**Dark Theme**

1. Normal Mode

image

2. Transparent Mode

image

### CODE REVIEW

**Comment by boradesanket13** [comment]
Great job with the digital clock, @Aravinthan-J ! Let's not make a transparent mode for the analog clock. Let me know if you have any doubt.

**Comment by Aravinthan-J** [comment]
> Let's not make a transparent mode for the analog clock

Actually @boradesanket13 !, I do nothing with an analog clock . I changed only in digital clock.

**Comment by boradesanket13** [comment]
Raise the PR once again. Will merge it

**Comment by Aravinthan-J** [comment]
Raised @boradesanket13  https://github.com/boradesanket13/miss-minute/pull/83

**Pull request closed without merging**
